"""Ticker -> sector mapping (IDX-IC style).

Two layers, curated first:

1. ``SECTOR_MAP`` — hand-maintained overrides for the liquid names we care
   about most. Always wins.
2. ``sector_lookup.json`` — generated by ``scripts/refresh_sector_map.py`` from
   Yahoo Finance sector/industry data, folded into the same buckets. Covers
   every emiten we hold prices for.

Anything in neither layer falls into ``FALLBACK_SECTOR`` ("Lainnya"). Before
the generated layer existed, ~3 of every 4 emiten landed there, which made the
sector analysis and the RRG chart misleading.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

# Canonical bucket vocabulary. Both layers must use these strings; the test
# suite fails if a new bucket shows up without being registered here.
BUCKETS: tuple[str, ...] = (
    "Perbankan",
    "Keuangan Non-Bank",
    "Asuransi",
    "Energi",
    "Batubara",
    "Logam & Mineral",
    "Properti",
    "Telkom & Internet",
    "Infrastruktur",
    "Konstruksi",
    "Transportasi & Logistik",
    "Konsumer Primer",
    "Konsumer Sekunder",
    "Agriculture",
    "Kesehatan",
    "Media & Hiburan",
    "Otomotif",
    "Industri Dasar & Kimia",
    "Utilitas",
    "Teknologi",
    "Retail",
    "Jasa & Industri",
    "Konglomerat",
)

FALLBACK_SECTOR = "Lainnya"

SECTOR_MAP: dict[str, str] = {
    # ---- Perbankan & Keuangan ----
    "BBCA": "Perbankan", "BBRI": "Perbankan", "BMRI": "Perbankan", "BBNI": "Perbankan",
    "BRIS": "Perbankan", "BBTN": "Perbankan", "BNGA": "Perbankan", "BRIN": "Perbankan",
    "NISP": "Perbankan", "PNBN": "Perbankan", "MEGA": "Perbankan", "ARTO": "Perbankan",
    "BBKP": "Keuangan Non-Bank", "BFIN": "Keuangan Non-Bank", "CRED": "Keuangan Non-Bank",
    "BTPS": "Perbankan", "AGRO": "Perbankan", "BJBR": "Perbankan", "BKSL": "Keuangan Non-Bank",
    "CYBR": "Keuangan Non-Bank", "NOBU": "Perbankan", "BVIC": "Keuangan Non-Bank",
    "PNLF": "Keuangan Non-Bank", "PFIN": "Keuangan Non-Bank", "MFIN": "Keuangan Non-Bank",
    "AHAP": "Asuransi", "LIFE": "Asuransi", "ASRM": "Asuransi", "AMAG": "Asuransi",
    "PRDA": "Asuransi", "HEAL": "Asuransi", "AHPC": "Asuransi",
    # ---- Energi & Batubara ----
    "PGAS": "Energi", "MEDC": "Energi", "ADRO": "Batubara", "ITMG": "Batubara",
    "PTBA": "Batubara", "BYAN": "Batubara", "INDY": "Batubara", "HRUM": "Batubara",
    "PTRO": "Batubara", "BSSR": "Batubara", "DEWA": "Energi", "ENRG": "Energi",
    "COAL": "Batubara", "KKGI": "Batubara", "GEMS": "Batubara", "SMMT": "Batubara",
    "DSSA": "Energi", "RUIS": "Energi", "RAJA": "Energi",
    # ---- Logam & Mineral ----
    "ANTM": "Logam & Mineral", "INCO": "Logam & Mineral", "MDKA": "Logam & Mineral",
    "NCKL": "Logam & Mineral", "TINS": "Logam & Mineral", "PSAB": "Logam & Mineral",
    "BRMS": "Logam & Mineral", "ARCI": "Logam & Mineral", "DKFT": "Logam & Mineral",
    "ZINC": "Logam & Mineral", "NICL": "Logam & Mineral", "TMSO": "Logam & Mineral",
    "MBMA": "Logam & Mineral", "CNKO": "Logam & Mineral", "GOLD": "Logam & Mineral",
    "EMAS": "Logam & Mineral", "AMMN": "Logam & Mineral", "MRAT": "Logam & Mineral",
    # ---- Properti & Real Estat ----
    "BSDE": "Properti", "SMRA": "Properti", "PWON": "Properti", "CTRA": "Properti",
    "ASRI": "Properti", "DMAS": "Properti", "PANI": "Properti", "ARNA": "Properti",
    "BEST": "Properti", "DPUM": "Properti", "GPRA": "Properti", "KOTA": "Properti",
    "LPKR": "Properti", "MDLN": "Properti", "NIKL": "Properti", "RSCH": "Properti",
    "APLN": "Properti", "DILD": "Properti", "JRPT": "Properti", "OMRE": "Properti",
    "IMPC": "Properti", "BIPP": "Properti", "BUVA": "Properti", "CBRE": "Properti",
    # ---- Telkom & Internet ----
    "TLKM": "Telkom & Internet", "ISAT": "Telkom & Internet", "EXCL": "Telkom & Internet",
    "BUKA": "Telkom & Internet", "EMTK": "Telkom & Internet", "MTDL": "Telkom & Internet",
    "OASA": "Telkom & Internet", "TFAS": "Telkom & Internet", "WIFI": "Telkom & Internet",
    "INET": "Telkom & Internet",
    # ---- Infrastruktur & Konstruksi ----
    "TOWR": "Infrastruktur", "MTEL": "Infrastruktur", "TBIG": "Infrastruktur",
    "BALI": "Infrastruktur", "LINK": "Infrastruktur", "JSMR": "Infrastruktur",
    "WIKA": "Konstruksi", "PTPP": "Konstruksi", "ADHI": "Konstruksi", "WSBP": "Konstruksi",
    "WSKT": "Konstruksi", "ACES": "Infrastruktur", "SHIP": "Infrastruktur",
    "JECC": "Infrastruktur", "CMNP": "Infrastruktur", "IPCM": "Infrastruktur",
    "YULE": "Konstruksi",
    # ---- Transportasi & Logistik ----
    "UNTR": "Transportasi & Logistik", "GIAA": "Transportasi & Logistik",
    "SMDR": "Transportasi & Logistik", "TMAS": "Transportasi & Logistik",
    "AKRA": "Transportasi & Logistik", "PSSI": "Transportasi & Logistik",
    "HAIS": "Transportasi & Logistik", "BIRD": "Transportasi & Logistik",
    "SAPX": "Transportasi & Logistik", "ELPI": "Transportasi & Logistik",
    "RIGS": "Transportasi & Logistik", "BULL": "Transportasi & Logistik",
    "KALI": "Transportasi & Logistik", "BPTR": "Transportasi & Logistik",
    "ASSA": "Transportasi & Logistik", "SDMU": "Transportasi & Logistik",
    # ---- Konsumer Primer & Agriculture ----
    "AMRT": "Konsumer Primer", "ICBP": "Konsumer Primer", "INDF": "Konsumer Primer",
    "CPIN": "Konsumer Primer", "JPFA": "Konsumer Primer", "AALI": "Agriculture",
    "LSIP": "Agriculture", "SSMS": "Agriculture", "TAPG": "Konsumer Primer",
    "STAA": "Konsumer Primer", "BWPT": "Agriculture", "DSNG": "Agriculture",
    "SIMP": "Konsumer Primer", "GGRM": "Konsumer Primer", "HMSP": "Konsumer Primer",
    "WIIM": "Konsumer Primer", "RMKE": "Agriculture", "TBLA": "Agriculture",
    "SMAR": "Agriculture", "UNVR": "Konsumer Primer", "MYOR": "Konsumer Primer",
    "SKLT": "Konsumer Primer", "CAMP": "Konsumer Primer", "ROTI": "Konsumer Primer",
    # ---- Kesehatan ----
    "KLBF": "Kesehatan", "KAEF": "Kesehatan", "SIDO": "Kesehatan", "DVLA": "Kesehatan",
    "PYFA": "Kesehatan", "MIKA": "Kesehatan", "SILO": "Kesehatan", "SAME": "Kesehatan",
    # ---- Konsumer Sekunder, Media, Otomotif ----
    "MERK": "Konsumer Sekunder", "SCMA": "Media & Hiburan", "MNCN": "Media & Hiburan",
    "FILM": "Media & Hiburan", "MSIN": "Media & Hiburan", "VIVA": "Media & Hiburan",
    "CMRY": "Media & Hiburan", "BAYU": "Konsumer Sekunder", "AUTO": "Otomotif",
    "ASII": "Otomotif", "IMAS": "Otomotif", "GJTL": "Otomotif", "INDS": "Otomotif",
    "BOLT": "Otomotif",
    # ---- Industri Dasar & Kimia ----
    "INKP": "Industri Dasar & Kimia", "TKIM": "Industri Dasar & Kimia",
    "BRPT": "Industri Dasar & Kimia", "SMGR": "Industri Dasar & Kimia",
    "INTP": "Industri Dasar & Kimia", "UNSP": "Industri Dasar & Kimia",
    "ESSA": "Industri Dasar & Kimia", "AGII": "Industri Dasar & Kimia",
    "BAJA": "Industri Dasar & Kimia", "KRAS": "Industri Dasar & Kimia",
    "SRSN": "Industri Dasar & Kimia", "TPIA": "Industri Dasar & Kimia",
    "AGIJ": "Industri Dasar & Kimia", "MDIA": "Industri Dasar & Kimia",
    "EAST": "Industri Dasar & Kimia", "KIJA": "Industri Dasar & Kimia",
    # ---- Utilitas & Energi Terbarukan ----
    "PGEO": "Utilitas", "KEEN": "Utilitas", "POWR": "Utilitas", "CITA": "Utilitas",
    "BREN": "Utilitas", "ATPK": "Utilitas", "GLVA": "Utilitas",
    # ---- Teknologi ----
    "COIN": "Teknologi", "DMMX": "Teknologi", "AXIO": "Teknologi", "IOTF": "Teknologi",
    # ---- Retail ----
    "MAPA": "Retail", "RALS": "Retail", "LPPF": "Retail", "ERAJ": "Retail",
    "DOOH": "Retail", "MPMX": "Retail", "CSAP": "Retail", "WAPO": "Retail",
    "WINS": "Retail",
    # ---- Overrides for emiten Yahoo has no sector/industry for (delisted,
    #      suspended, or renamed tickers). Verified against the company name. ----
    "ARMY": "Properti", "BOSS": "Batubara", "BTEL": "Telkom & Internet",
    "CBMF": "Industri Dasar & Kimia", "COWL": "Properti", "CPRI": "Properti",
    "DEAL": "Transportasi & Logistik", "DUCK": "Konsumer Sekunder",
    "ENVY": "Teknologi", "ETWA": "Industri Dasar & Kimia", "GAMA": "Properti",
    "GOLL": "Agriculture", "GOTOM": "Teknologi", "HKMU": "Logam & Mineral",
    "HOME": "Konsumer Sekunder", "HOTL": "Konsumer Sekunder", "IIKP": "Agriculture",
    "JSKY": "Industri Dasar & Kimia", "KAYU": "Agriculture",
    "KBRI": "Industri Dasar & Kimia", "LAPD": "Utilitas", "LCGP": "Properti",
    "LMAS": "Batubara", "MABA": "Batubara", "MAGP": "Agriculture",
    "MASA": "Otomotif", "META": "Infrastruktur", "MTRA": "Properti",
    "NUSA": "Properti", "OCAP": "Keuangan Non-Bank", "PLAS": "Keuangan Non-Bank",
    "POOL": "Keuangan Non-Bank", "POSA": "Properti", "PURE": "Logam & Mineral",
    "RIMO": "Properti", "SCPI": "Kesehatan", "SIMA": "Energi",
    "SKYB": "Media & Hiburan", "SMRU": "Batubara", "SRIL": "Konsumer Sekunder",
    "SUGI": "Energi", "TDPM": "Industri Dasar & Kimia", "TECH": "Teknologi",
    "TRAM": "Energi", "TRIL": "Jasa & Industri", "TRIO": "Retail",
    "UNIT": "Konsumer Sekunder",
}

_LOOKUP_PATH = Path(__file__).with_name("sector_lookup.json")


@lru_cache(maxsize=1)
def generated_map() -> dict[str, str]:
    """The generated layer, loaded once. Missing/corrupt file -> empty map."""
    try:
        raw = json.loads(_LOOKUP_PATH.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError):
        return {}
    sectors = raw.get("sectors")
    if not isinstance(sectors, dict):
        return {}
    return {str(k): str(v) for k, v in sectors.items()}


def sector_for(code: str) -> str:
    """Curated override, else the generated lookup, else "Lainnya"."""
    upper = code.upper()
    curated = SECTOR_MAP.get(upper)
    if curated:
        return curated
    return generated_map().get(upper, FALLBACK_SECTOR)


def coverage(codes: object | None = None) -> dict[str, object]:
    """How much of ``codes`` (any iterable, defaults to the curated keys) is mapped."""
    universe = list(codes) if codes is not None else sorted(set(SECTOR_MAP))
    generated = generated_map()
    curated = sum(1 for c in universe if c in SECTOR_MAP)
    fresh = sum(1 for c in universe if c not in SECTOR_MAP and c in generated)
    return {
        "total": len(universe),
        "curated": curated,
        "generated": fresh,
        "unmapped": len(universe) - curated - fresh,
        "mapped_pct": round(100 * (curated + fresh) / len(universe), 1) if universe else 0.0,
    }
